/* tslint:disable */
/* eslint-disable */
/**
 * The Coaxial API
 * The Coaxial REST API. Please see https://docs.coaxial.ai for more details.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: team@coaxial.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/auth-integration-api';
export * from './api/data-integration-api';
export * from './api/function-api';
export * from './api/model-integration-api';
export * from './api/provision-api';

import { AuthIntegrationApi } from './api/auth-integration-api';
import { DataIntegrationApi } from './api/data-integration-api';
import { FunctionApi } from './api/function-api';
import { ModelIntegrationApi } from './api/model-integration-api';
import { ProvisionApi } from './api/provision-api';

import { Configuration, ConfigurationParameters } from './configuration';

export class CoaxialApi {

    protected configuration: Configuration | undefined;
    public AuthIntegration : AuthIntegrationApi | undefined
    public DataIntegration : DataIntegrationApi | undefined
    public Function : FunctionApi | undefined
    public ModelIntegration : ModelIntegrationApi | undefined
    public Provision : ProvisionApi | undefined
    

    constructor(param: ConfigurationParameters = {}) {
        
        this.configuration = new Configuration(param);
        this.AuthIntegration = new AuthIntegrationApi(this.configuration)
        this.DataIntegration = new DataIntegrationApi(this.configuration)
        this.Function = new FunctionApi(this.configuration)
        this.ModelIntegration = new ModelIntegrationApi(this.configuration)
        this.Provision = new ProvisionApi(this.configuration)
        
    }
}