/* tslint:disable */
/* eslint-disable */
/**
 * The Coaxial API
 * The Coaxial REST API. Please see https://docs.coaxial.ai for more details.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: team@coaxial.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CallModelRequest
 */
export interface CallModelRequest {
    /**
     * 
     * @type {any}
     * @memberof CallModelRequest
     */
    'prompt': any;
    /**
     * 
     * @type {any}
     * @memberof CallModelRequest
     */
    'user_id': any;
}

