/* tslint:disable */
/* eslint-disable */
/**
 * The Coaxial API
 * The Coaxial REST API. Please see https://docs.coaxial.ai for more details.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: team@coaxial.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The Function model
 * @export
 * @interface Function
 */
export interface Function {
    /**
     * 
     * @type {any}
     * @memberof Function
     */
    'coaxial_id': any;
    /**
     * 
     * @type {any}
     * @memberof Function
     */
    'description': any;
    /**
     * 
     * @type {any}
     * @memberof Function
     */
    'function_name': any;
    /**
     * 
     * @type {any}
     * @memberof Function
     */
    'id'?: any;
}

