/* tslint:disable */
/* eslint-disable */
/**
 * The Coaxial API
 * The Coaxial REST API. Please see https://docs.coaxial.ai for more details.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: team@coaxial.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Model } from './model';

/**
 * 
 * @export
 * @interface IntegrateCustomModelResponse
 */
export interface IntegrateCustomModelResponse {
    /**
     * 
     * @type {Model}
     * @memberof IntegrateCustomModelResponse
     */
    'model': Model;
}

