/* tslint:disable */
/* eslint-disable */
/**
 * The Coaxial API
 * The Coaxial REST API. Please see https://docs.coaxial.ai for more details.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: team@coaxial.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The LLM model
 * @export
 * @interface Model
 */
export interface Model {
    /**
     * 
     * @type {any}
     * @memberof Model
     */
    'coaxial_id': any;
    /**
     * 
     * @type {any}
     * @memberof Model
     */
    'id'?: any;
    /**
     * 
     * @type {any}
     * @memberof Model
     */
    'integration_type': any;
    /**
     * 
     * @type {any}
     * @memberof Model
     */
    'model_name': any;
}

