/* tslint:disable */
/* eslint-disable */
/**
 * The Coaxial API
 * The Coaxial REST API. Please see https://docs.coaxial.ai for more details.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: team@coaxial.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserInfo } from './user-info';

/**
 * The User model
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {any}
     * @memberof User
     */
    'baseUser_id': any;
    /**
     * 
     * @type {any}
     * @memberof User
     */
    'email': any;
    /**
     * 
     * @type {any}
     * @memberof User
     */
    'first': any;
    /**
     * 
     * @type {any}
     * @memberof User
     */
    'id': any;
    /**
     * 
     * @type {any}
     * @memberof User
     */
    'imported_at': any;
    /**
     * 
     * @type {any}
     * @memberof User
     */
    'last': any;
    /**
     * 
     * @type {any}
     * @memberof User
     */
    'modified_at': any;
    /**
     * 
     * @type {any}
     * @memberof User
     */
    'resource_list': any;
    /**
     * 
     * @type {UserInfo}
     * @memberof User
     */
    'source_metadata': UserInfo;
}

